apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-get-service
spec:
  selector:
    matchLabels:
      app: todo-get-service
  replicas: 3
  template:
    metadata:
      labels:
        app: todo-get-service
    spec:
      containers:
      - name: todo-get-service
        image: todoaksacrspsingh.azurecr.io/todo-get-service:v1
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:todo-aksmssqlserver007.database.windows.net,1433;Database=todo-aksmssqldb007;Uid=achinta;Pwd=Satya@834068;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

