apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-get-service
  labels:
    app: todo-get-service
spec:
  ingressClassName: todo-aks-appgw    #azure-application-gateway
  rules:
  - host: todo-get-service.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: get
            port: 
              number: 80