apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete
spec:
  selector:
    matchLabels:
      app: delete
  replicas: 3
  template:
    metadata:
      labels:
        app: delete
    spec:
      containers:
      - name: delete
        image: todoappconatinerregistry.azurecr.io/todo-ui-service:v2
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:heromssqlserver007.database.windows.net,1433;Database=heromssqldb007;Uid=achinta;Pwd=Raju@834068;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

