apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui-service
spec:
  selector:
    matchLabels:
      app: todo-ui-service
  replicas: 5
  template:
    metadata:
      labels:
        app: todo-ui-service
    spec:
      containers:
      - name: todo-ui-service
        image: todoappconatinerregistry.azurecr.io/todo-ui-service:v2
        ports:
        - containerPort: 80

