apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ui-service
  labels:
    app: todo-ui-service
spec:
  ingressClassName: todo-aks-appgw
  rules:
  - host: todo-ui-service.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: todo-ui-service
            port: 
              number: 80